/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef, useEffect} from "react";
import {useGLTF, useAnimations} from "@react-three/drei";

export default function Model({...props}) {
  const group = useRef();
  const {nodes, materials, animations} = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/pig-project-ea5ab.appspot.com/o/massageGun%2FgunHead3.glb?alt=media&token=9ce84f57-13fe-4615-adb8-da6d6dedc0e8"
  );
  const {actions} = useAnimations(animations, group);
  useEffect(() => {
    actions.Animation6.play();
    actions.Animation6.repetitions = 1;
    actions.Animation6.clampWhenFinished = true;
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="head3" position={[0.4, 0, 0]} rotation={[0, 0, 0.7]}>
          <mesh
            geometry={nodes.圓柱體010.geometry}
            material={materials["材質.006"]}
          />
          <mesh
            geometry={nodes.圓柱體010_1.geometry}
            material={materials["材質.005"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/pig-project-ea5ab.appspot.com/o/massageGun%2FgunHead3.glb?alt=media&token=9ce84f57-13fe-4615-adb8-da6d6dedc0e8"
);
