/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef, useEffect} from "react";
import {useGLTF, useAnimations} from "@react-three/drei";

export default function Model({...props}) {
  const group = useRef();
  const {nodes, materials, animations} = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/pig-project-ea5ab.appspot.com/o/massageGun%2FgunPedestal.glb?alt=media&token=2b01df3c-6f6f-4eca-bb70-6c07f926d340"
  );
  const {actions} = useAnimations(animations, group);
  useEffect(() => {
    actions.Animation9.play();
    actions.Animation9.repetitions = 1;
    actions.Animation9.clampWhenFinished = true;
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh
          name="pedestal"
          geometry={nodes.pedestal.geometry}
          material={materials["材質.003"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/pig-project-ea5ab.appspot.com/o/massageGun%2FgunPedestal.glb?alt=media&token=2b01df3c-6f6f-4eca-bb70-6c07f926d340"
);
