/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef, useEffect} from "react";
import {useGLTF, useAnimations} from "@react-three/drei";

export default function Model({...props}) {
  const group = useRef();
  const {nodes, materials, animations} = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/pig-project-ea5ab.appspot.com/o/RubberTube%2FtubeGrip2.glb?alt=media&token=4db80790-2cbe-42f0-a538-bbca66636b4c"
  );
  const {actions} = useAnimations(animations, group);
  useEffect(() => {
    actions.Animation3.play();
    actions.Animation3.repetitions = 1;
    actions.Animation3.clampWhenFinished = true;
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="grip2">
          <mesh
            geometry={nodes.圓柱體004.geometry}
            material={materials["材質.004"]}
          />
          <mesh
            geometry={nodes.圓柱體004_1.geometry}
            material={materials["材質.002"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/pig-project-ea5ab.appspot.com/o/RubberTube%2FtubeGrip2.glb?alt=media&token=4db80790-2cbe-42f0-a538-bbca66636b4c"
);
