/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from "react";
import {useGLTF, useAnimations} from "@react-three/drei";

export default function Model({...props}) {
  const group = useRef();
  const {nodes, materials, animations} = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/pig-project-ea5ab.appspot.com/o/Shoes%2FshoesAnim.glb?alt=media&token=960d3ef9-1819-42a4-a508-7afad829e7d6"
  );
  const {actions} = useAnimations(animations, group);
  console.log(actions);
  console.log(animations);
  useEffect(() => {
    // actions.shoesAnim
    console.log(actions);
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Air_cushion.geometry}
        material={materials["Material.013"]}
        position={[-0.01, 1.34, -0.53]}
        scale={[0.24, 0.21, 0.24]}
      />
      <mesh
        geometry={nodes.outsole.geometry}
        material={materials["Material.008"]}
        position={[-0.01, 1.34, -0.53]}
        rotation={[Math.PI / 2, -1.54, Math.PI / 2]}
        scale={0.16}
      />
      <group position={[-0.01, 1.34, -0.53]} scale={0.04}>
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          geometry={nodes.Plane001_2.geometry}
          material={materials["Material.009"]}
        />
      </group>
      <group
        position={[-0.01, 1.34, -1.55]}
        rotation={[-Math.PI / 2, 1.57, 0]}
        scale={0.11}
      >
        <mesh
          geometry={nodes.Plane003.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          geometry={nodes.Plane003_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <mesh
        geometry={nodes.sock.geometry}
        material={materials["Material.004"]}
        position={[-0.01, 1.34, -0.53]}
        scale={[0.24, 0.24, 0.24]}
      />
      <mesh
        geometry={nodes.socktrim.geometry}
        material={materials["Material.002"]}
        position={[-0.01, 1.34, -0.53]}
        scale={[0.24, 0.24, 0.24]}
      />
      <mesh
        geometry={nodes.socktrimOnShoes.geometry}
        material={materials["Material.003"]}
        position={[-0.01, 1.34, -0.53]}
        scale={[0.24, 0.24, 0.24]}
      />
      <mesh
        name="sole"
        geometry={nodes.sole.geometry}
        material={materials["Material.005"]}
        position={[-0.01, 1.34, -0.53]}
        scale={[0.24, 0.21, 0.24]}
      />
    </group>
  );
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/pig-project-ea5ab.appspot.com/o/Shoes%2FshoesAnim.glb?alt=media&token=960d3ef9-1819-42a4-a508-7afad829e7d6"
);
