/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef, useEffect} from "react";
import {useGLTF, useAnimations} from "@react-three/drei";

export default function Model({...props}) {
  const group = useRef();
  const {nodes, materials, animations} = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/pig-project-ea5ab.appspot.com/o/treadmill%2FmillShell.glb?alt=media&token=983f5d01-ebd4-4c50-9553-cd2a4ac8d7d2"
  );
  const {actions} = useAnimations(animations, group);
  useEffect(() => {
    actions.Animation11.play();
    actions.Animation11.repetitions = 1;
    actions.Animation11.clampWhenFinished = true;
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="shell">
          <mesh geometry={nodes.立方體007.geometry} material={materials.材質} />
          <mesh
            geometry={nodes.立方體007_1.geometry}
            material={materials["材質.003"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/pig-project-ea5ab.appspot.com/o/treadmill%2FmillShell.glb?alt=media&token=983f5d01-ebd4-4c50-9553-cd2a4ac8d7d2"
);
