/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef, useEffect} from "react";
import {useGLTF, useAnimations} from "@react-three/drei";

export default function Model({...props}) {
  const group = useRef();
  const {nodes, materials, animations} = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/pig-project-ea5ab.appspot.com/o/treadmill%2FmillSpringShaft.glb?alt=media&token=5d05e6a0-61c9-499c-b35d-f0bd4950c4ec"
  );
  const {actions} = useAnimations(animations, group);
  useEffect(() => {
    actions.Animation13.play();
    actions.Animation13.repetitions = 1;
    actions.Animation13.clampWhenFinished = true;
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh
          name="springShaft"
          geometry={nodes.springShaft.geometry}
          material={materials.軸灰}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/pig-project-ea5ab.appspot.com/o/treadmill%2FmillSpringShaft.glb?alt=media&token=5d05e6a0-61c9-499c-b35d-f0bd4950c4ec"
);
