/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef, useEffect} from "react";
import {useGLTF, useAnimations} from "@react-three/drei";

export default function Model({...props}) {
  const group = useRef();
  const {nodes, materials, animations} = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/pig-project-ea5ab.appspot.com/o/GreenBike%2FbikeShell.glb?alt=media&token=a63e9091-08e6-40a8-8b63-d020c6c8aa37"
  );
  const {actions} = useAnimations(animations, group);
  useEffect(() => {
    actions.Animation10.play();
    actions.Animation10.repetitions = 1;
    actions.Animation10.clampWhenFinished = true;
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="shell">
          <mesh
            geometry={nodes.圓柱體003.geometry}
            material={materials["材質.010"]}
          />
          <mesh
            geometry={nodes.圓柱體003_1.geometry}
            material={materials["材質.006"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/pig-project-ea5ab.appspot.com/o/GreenBike%2FbikeShell.glb?alt=media&token=a63e9091-08e6-40a8-8b63-d020c6c8aa37"
);
